### ISSUE TITLE
Booting k3os on armv7.

### ISSUE THREAD

**Issue by vthakur7f** [rancher/k3os#138] opened 2019-06-28 20:23 UTC
## Issue
Failing to boot armv7 board with k3os.

## Procedure
Followed the ARM Overlay Installation i.e used armv7 kernel (had to enable support for squashfs and SCSI modules) and than changed the bootcmd command to mount rootfs as read write but ended up few issue like :
1.   ERRO[0000] json: cannot unmarshal number into Go struct field K3OS.sysctls of type string.
2.  ERROR: sysctl failed to start.
3.  error mounting mqueue to /dev/mqueue: no such device.

I am not sure if its worth mentioning but I am using sample config.yaml as k3os configuration file.

## HW 
SAMA5D27 SOM1 EK

## Linux Kernel
 v4.19.x-sama5-armv7 from https://github.com/RobertCNelson/armv7_devel [](https://github.com/RobertCNelson/armv7_devel)

## Logs
 
*  Welcome to k3OS v0.2.0
[    3.450000] mmc0: Tuning timeout, falling back to fixed sampling clock
chpasswd: password for 'rancher' changed
2012/01/01 02:31:51 error making directory /var/lock: mkdir /var/lock: file exists
2012/01/01 02:31:51 error mounting mqueue to /dev/mqueue: no such device
2012/01/01 02:31:51 cannot write to /sys/fs/cgroup/memory/memory.use_hierarchy: open /sys/fs/cgroup/memory/memory.use_hierarchy: no such file or directory
 *  Bootstrapped
 *  Running mode: local
 *  Booting system
[    8.130000] mmc0: Tuning timeout, falling back to fixed sampling clock
ERRO[0000] json: cannot unmarshal number into Go struct field K3OS.sysctls of type string

   OpenRC 0.39.2.7e1d41d609 is starting up Linux 4.19.15-sama5-armv7-r2 (armv7l)

 * /proc is already mounted
 * /run/openrc: creating directory
 * /run/lock: creating directory
 * /run/lock: correcting owner
 * Caching service dependencies ... [ ok ]
 * Clock skew detected with `(null)'
 * Adjusting mtime of `/run/openrc/deptree' to Sat May  4 06:02:03 2019

 * WARNING: clock skew detected!
 * Remounting devtmpfs on /dev ... [ ok ]
 * Starting busybox mdev ... [ ok ]
 * Loading hardware drivers ... [ ok ]
 * Checking local filesystems  ... [ ok ]
 * Remounting filesystems ... [ ok ]
 * Mounting local filesystems ... [ ok ]
 * WARNING: clock skew detected!
 * Loading modules ... [ ok ]
 * Setting system clock using the hardware clock [UTC] ... [ ok ]
 * Starting busybox acpid ... [ ok ]
 * Configuring kernel parameters ...sysctl: cannot stat /proc/sys/net/ipv4/tcp_syncookies: error code 2
 * Unable to configure some kernel parameters
 [ !! ]
 * ERROR: sysctl failed to start
 * Creating user login records ... [ ok ]
 * Starting D-BUS system messagebus ... [ ok ]
 * /run/connman: creating directory
 [ ok ]
 * Starting connman ... [ ok ]
 * Starting haveged ... [ ok ]
haveged: haveged starting up
 * Setting hostname ... [ ok ]
 * Starting issue ... [ ok ]
 * Starting busybox syslog ... [ ok ]
 * WARNING: clock skew detected!
 * Configuring kernel parameters ...sysctl: cannot stat /proc/sys/net/ipv4/tcp_syncookies: error code 2
 * Unable to configure some kernel parameters
 [ !! ]
 * ERROR: sysctl failed to start
 * Starting issue ... [ ok ]
 * Starting ccapply ...ERRO[0000] json: cannot unmarshal number into Go struct field K3OS.sysctls of type string
 [ ok ]
 * Checking open-iSCSI configuration ... * Loading iSCSI modules ... * Loading libiscsi ... [ ok ]
 * Loading scsi_transport_iscsi ... [ ok ]
 * Loading iscsi_tcp ... [ ok ]
 * Starting iscsid ... * Setting up iSCSI targets ...iscsiadm: No records found
 [ ok ]
 * Starting issue ... [ ok ]
 * Starting sshd ... [ ok ]
 * Starting local ... [ ok ]
ERRO[0000] json: cannot unmarshal number into Go struct field K3OS.sysctls of type string 

Any help would be great.

**Comment by Rick-Jongbloed** [comment] 2019-08-24 11:54
This looks relaxed to https://github.com/rancher/k3os/issues/95.

**Comment by davidnuzik** [comment] 2019-09-24 17:41
Could you retry with the latest RC? https://github.com/rancher/k3os/releases
This should be fixed now.

**Comment by davidnuzik** [comment] 2019-11-01 18:42
If the issue is still observed let us know. We haven't heard back so I'm closing the issue for now; should be fixed.

**Closed** 2019-11-01 18:42 UTC
Labels: [zube]: Awaiting Feedback, area/arm, area/configuration, kind/bug
