### ISSUE TITLE
k3s failure on Odroid-C2 (arm64)

### ISSUE THREAD

**Issue by pagong** [rancher/k3os#120] opened 2019-06-07 17:55 UTC
I've finally managed to get `k3os` v0.2.1 running on an arm64 board: odroid-c2

I started with the ubuntu-18.4 image of hardkernel and continued with the overlay installation method by extracting the arm64 rootfs image to directories /k3os and /sbin.
I placed a config.yaml into /k3os/system and changed the kernel command line to use `rw` and `k3os.debug`.

At boot time a lot of errors are thrown, but `k3os` starts running, more or less.
And I even manged to start `ntpd -p pool.ntp.org` to get valid date and time.

But I've never managed to get `k3s` v0.5.0 working properly:
It always throws `exec format error` whenever it's called with parameters `server`, `agent`, `kubectl` or `crictl`.

Dear Rancher folks: do you have any idea how to proceed further?

![k3s-exec-format-error](https://user-images.githubusercontent.com/4641150/59123647-01b3c300-895e-11e9-8c40-da96b030ce33.JPG)

**Comment by pagong** [comment] 2019-06-08 09:52
**Update**:  some of the failures on odroid-c2 are probably due to the use of non-premium sd cards.
Although I was using class10 sdhc cards, the o-c2 seems to be especially sensitive to sd card quality.

In the meantime I've disabled UHS mode in `boot.ini` with `setenv disableuhs "true"` and switched to 'sandisk' branded  cards. And I've included lots of `sync` commands in my installation scripts.

The results are more consistent now: 
`k3s` does no longer complain about `exec format error`.
Time gets synced with `pool.ntp.org` when command  `service ntpd start` is used.
Btw. NTP should be activated by default.

But `k3s` still does not work properly: the `server` crashes with a kernel dump after several seconds of initialization and then `k3os` filesystem needs repairing at the next boot. 
I'm going to tweak the `boot.ini` of the o-c2 a bit more, in order to get a full log of the serial console.

**Comment by ubergeek801** [comment] 2019-07-01 05:43
I'm afraid I can't help directly, but I have a couple of C2's (which do not run k3os) and a number of N2's (which do). All of them use eMMC which has been highly reliable for me. Have you tried using eMMC instead of SD?

**Comment by zimme** [comment] 2019-07-11 22:16
Got k3os up and running on Odroid-c2 and Odroid-c1+ using Armbian and arm overlay installation.

Armbian has newer kernels then Hardkernel's own ubuntu dist. which might be why I don't get the same issues as you did.

**Comment by davidnuzik** [comment] 2019-09-24 18:02
Could we ask you to take a look again in the latest rc we have up? We made some changes and this should work now (Connman). https://github.com/rancher/k3os/releases/tag/v0.3.0-rc2

**Comment by pagong** [comment] 2019-09-27 11:47
As I have repurposed the O-C2 board for Hass.OS, it will take me some time to get another O-C2 ready.
Anyway, it is good news to hear, that Rancher has resumed development for k3os :-)

**Comment by davidnuzik** [comment] 2019-11-01 18:43
This should be fixed; if the issue is still happening let us know so we can re-open the issue.

**Closed by davidnuzik** 2019-11-01 18:43 UTC
Labels: [zube]: Awaiting Feedback
