### ISSUE TITLE
failed to get sandbox image "k8s.gcr.io/pause:3.1"

### ISSUE THREAD

**Issue by myvker** [rancher/k3os#155] opened 2019-08-15 12:19 UTC
RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout
/var/log/k3s-service.log:E0815 10:17:20.131048    2832 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "coredns-695688789-rnr6x_kube-system(cb498210-bf45-11e9-887a-000c296837ee)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.203.82:443: i/o timeout

**Comment by arnaubennassar** [comment] 2019-08-15 19:13
Similar problem here:

Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: x509: certificate has expired or is not yet valid

**Comment by hopik007** [comment] 2019-08-27 16:17
Same issue for me. I am from corporate proxy. I have manually pull pause:3.1 image via `ctr`

`root@10:/etc/cni/net.d# ctr image list
REF                  TYPE                                                 DIGEST                                                                  SIZE      PLATFORMS   LABELS
k8s.gcr.io/pause:3.1 application/vnd.docker.distribution.manifest.v2+json sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610 308.1 KiB linux/amd64 -`

But issue still persist.

**Comment by dweomer** [comment] 2019-09-09 02:18
@myvker and @arnaubennassar are you running behind a proxy as @hopik007 has shared? If you are using `k30s`.`environment`.`http_proxy` and `k30s`.`environment`.`https_proxy` envvars as shown in the [sample `config.yaml in the readme`](https://github.com/rancher/k3os#sample-configyaml) and still having the same issue please let me know if you are running local/cloud, baremetal/vm

**Comment by dweomer** [comment] 2019-09-09 17:04
Looks like `k3s.environment` in `config.yaml` may be foiled by #98

**Comment by dweomer** [comment] 2019-09-21 21:10
@myvker @arnaubennassar @hopik007 I believe I've got a fix for this on master that ought to land in a release early next week.

**Comment by Pacifique2** [comment] 2019-09-23 15:26
@dweomer , I've been dealing with the same issue since two weeks ago. All my pods are no long running as usual on k3s cluster. The events show that i have that issue posted by @myvker. Woud you  please let me know if it's a new issue within k3s ? and whether it has been fixed up to now ?

**Comment by dweomer** [comment] 2019-09-23 23:13
@Pacifique2 I don't know that the problem is with k3s as there were some outstanding issues with DNS and networking in k3OS that I believe have been addressed by the latest release candidate, [v0.3.0-rc2](https://github.com/rancher/k3os/releases/tag/v0.3.0-rc2).

**Comment by Pacifique2** [comment] 2019-09-24 14:46
@dweomer Thank you for your prompt reply. I get your point. I'll check about that release.

**Comment by davidnuzik** [comment] 2019-11-01 18:42
This should be resolved in the latest release. If the issue remains let us know and we can re-open the issue.

**Closed by davidnuzik** 2019-11-01 18:43 UTC
Labels: [zube]: Awaiting Feedback, area/configuration, area/installation, area/networking, kind/bug
