### ISSUE TITLE
Boot k3os iso from usb stick fails

### ISSUE THREAD

**Issue by pwFoo** [rancher/k3os#60] opened 2019-04-29 08:12 UTC
Hi,
I tried to boot k3os from usb stick (Dell Vostro notebook) and it fails with 
```
cat /proc/cmdline
for x in $(cat /proc/cmdline
case $x in 
for x in $(cat /proc/cmdline
case $x in 
for x in $(cat /proc/cmdline
case $x in 
for x in $(cat /proc/cmdline
case $x in 
for x in $(cat /proc/cmdline
case $x in 
'[' -z '' ']'
blkid -L K3=S_STATE
'[' -n '' ']'
'[' -n '' ']'
'[' -z '' ']'
pfatal Failed to determine boot mode
echo '[FATAL] Failed to determine boot mode'
[FATAL] Failed to determine boot mode
exit 1
rescue
...
```

Dropped to bash then.

**Comment by joharper54SEG** [comment] 2019-05-03 16:45
Having the same issue.  Trying to install on an Intel NUC.

**Comment by ibuildthecloud** [comment] 2019-05-04 21:25
Please try v0.2.0-rc6 should be fixed now.

**Comment by pwFoo** [comment] 2019-05-05 16:55
I get a new error message

![image](https://user-images.githubusercontent.com/333408/57197412-50d59500-6f67-11e9-9c49-7d83198b9171.png)

**Comment by joharper54SEG** [comment] 2019-05-06 13:47
I get the same "you need to load the kernel first" error with RC6.  Booting to livecd or rescue shell results in the same error.

**Comment by kylejeske** [comment] 2019-05-08 20:08
+1

I was able to get it to boot by changing the 'current' destination to 4.15.0-47-generic inside the grub entry.

when executing long list version of list sort against directory: /k3os/system/kernel/current, it shows empty. 

it seems there is something broken with the symlink.

**Comment by joharper54SEG** [comment] 2019-05-09 16:48
Thanks kylejeske!

I can confirm modifying the grub entry allow me to boot.  After installing to disk I had the same issue.  I solved by modifying /boot/grub/grub.cfg is the same manner.

![k3os-grub](https://user-images.githubusercontent.com/46793278/57471220-aefcc380-7258-11e9-8736-5e9c76a79cff.jpg)

**Comment by pwFoo** [comment] 2019-05-21 08:09
Boot iso form usb stick still fails.

```
error: not a directory.
error: disk 'loop0' not found
error: you need to load the kernel first
```

**Comment by pwFoo** [comment] 2019-05-21 08:09
Tested with latest release today.

**Comment by pwFoo** [comment] 2019-05-21 08:35
Maybe a problem with "rufus" to write the iso. Tested with dd mode it boots to shell.
Live booted from usb stick looks like just a installer and not a live system.

I'll install and test k3os now...

**Comment by davidnuzik** [comment] 2019-09-24 18:52
Is this still an issue? Sounds like with dd mode it booted.

**Comment by davidnuzik** [comment] 2019-11-01 18:45
Closing; if the issue is still observed let us know so we can re-open if necessary.

**Closed by davidnuzik** 2019-11-01 18:45 UTC
Labels: [zube]: Awaiting Feedback

**Comment by danielsand** [comment] 2020-03-24 21:41
dont use rufus to make the bootsable stick - fixed my problem

**Comment by gnoejuan** [comment] 2020-07-21 05:03
Which program did y'all use to make a bootable usb?

**Comment by cdeadspine** [comment] 2020-11-17 21:36
The Nightmare continues:
v0.19.2-dev.4
k3os-amd64.iso

No idea what usb creation tool to use:
```
Tried RUFUS to create bootable USB
   All combinations of "write iso image mode" / "write dd image mode" and GPT / MBR
      some of them will boot into LIVE mode fine, but none will boot from hard drive properly after INSTALL
        not sure how old the BIOS / hardware is, I think it mentions EFI somewhere in bios and when selecting boot but no mention of "UEFI" anywhere

      tried "partition mode: gpt" "iso image mode"
        edited /k3os/system/config.yaml
          "invalid independant arch ELF magic"
      
tried "partition mode: gpt" "DD mode"
        chose installer, reboot went back to live usb boot automatically
        re-installed from live
        still wont boot

  try https://www.balena.io/etcher/ instead of rufus
    no good

  try https://unetbootin.github.io/
    couldnt choose drive, manually cleaned and formatted fat32
    still couldnt choose drive

  try https://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/
    chose the last generic linux "grub"
    had to quick format the drive again for some reason?
      booted into "grub for dos"?? grub> prompt?
    try again, second last "unlisted linux"
      boot options dont look right, mentions something about casper, and selection wont work

```
